[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[workspace]
members = [
  "programs/kedolik-stake-lock-v1",
]

[features]
seeds = true
skip-lint = false

[test]
startup_wait = 10000

[scripts]
test = "../node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[programs.localnet]
kedolik_stake_lock = "6M6TzGRSRqYxYmAihrXgF6MrmrCJno4RK9mEDdtkanCW"

[programs.devnet]
kedolik_stake_lock = "6M6TzGRSRqYxYmAihrXgF6MrmrCJno4RK9mEDdtkanCW"
