[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[workspace]
members = [
  "programs/kedolik-locker-v1",
  "programs/kedolik-mint-wrapper-v1",
  "programs/kedolik-staking-v1",
]

[features]
seeds = true
skip-lint = false

[provider]
cluster = "devnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[programs.localnet]
locker = "9mtTTmx6ncn7FKfE9oyeiURctm2fZUN6kPLAbPLoXuvU"
quarry_mint_wrapper = "QMWoBmAyJLAsA1Lh9ugMTw2gciTihncciphzdNzdZYV"
quarry_mine = "QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB"

[programs.devnet]
locker = "9mtTTmx6ncn7FKfE9oyeiURctm2fZUN6kPLAbPLoXuvU"
